services:
  db:
    image: postgres:17.2-alpine3.21
    container_name: tradelens-flask-postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tradelens-flask-postgres
    ports:
      - "5431:5432"

  app:
    container_name: tradelens-flask
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5200:5000"
    depends_on:
      - db